steps:
  - label: ":eslint: Lint"
    key: lint
    plugins:
      - mise#v1.1.0: ~
    command: npm ci && npm run lint

  - label: ":typescript: Compile"
    key: compile
    plugins:
      - mise#v1.1.0: ~
    command: npm ci && npm run compile

  - label: ":vscode: Build package"
    key: build
    depends_on: ["lint", "compile"]
    plugins:
      - mise#v1.1.0: ~
    command: npm ci && npm run vscode:package
    artifact_paths:
      - "buildkite-*.vsix"
