cache:
  paths:
    - node_modules

steps:
  - label: ":npm: Install"
    key: install
    plugins:
      - mise#v1.1.0: ~
    command: npm ci

  - label: ":eslint: Lint"
    depends_on: install
    plugins:
      - mise#v1.1.0: ~
    command: npm run lint

  - label: ":typescript: Compile"
    depends_on: install
    plugins:
      - mise#v1.1.0: ~
    command: npm run compile

  - label: ":vscode: Test"
    depends_on: install
    plugins:
      - mise#v1.1.0: ~
    command: npm test
